# Generated by Django 5.2.6 on 2025-10-03 06:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqam +998xxxxxxx fromatida bo'lishi kerak.", regex='^\\+998\\d{9}$')]),
        ),
    ]
