# Generated by Django 5.2.6 on 2025-11-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
    ]
